// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRFV7agRCyJpckLeYOpEgzXlCqopvd_1A',
    appId: '1:86783075117:web:b12fe23883868512f6e9a4',
    messagingSenderId: '86783075117',
    projectId: 'latihanfirebase-12',
    authDomain: 'latihanfirebase-12.firebaseapp.com',
    databaseURL: 'https://latihanfirebase-12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanfirebase-12.firebasestorage.app',
    measurementId: 'G-BSC8GGZBNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFtv6XJ-zsKFYE9u29YrKCFGF1z1598XQ',
    appId: '1:86783075117:android:782bb2515d5b7394f6e9a4',
    messagingSenderId: '86783075117',
    projectId: 'latihanfirebase-12',
    databaseURL: 'https://latihanfirebase-12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanfirebase-12.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqi0psdNlXIwAsY3YTAgqX69n58_J6SEU',
    appId: '1:86783075117:ios:c0600658b9462906f6e9a4',
    messagingSenderId: '86783075117',
    projectId: 'latihanfirebase-12',
    databaseURL: 'https://latihanfirebase-12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanfirebase-12.firebasestorage.app',
    iosBundleId: 'com.example.latihanfirebase',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqi0psdNlXIwAsY3YTAgqX69n58_J6SEU',
    appId: '1:86783075117:ios:c0600658b9462906f6e9a4',
    messagingSenderId: '86783075117',
    projectId: 'latihanfirebase-12',
    databaseURL: 'https://latihanfirebase-12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanfirebase-12.firebasestorage.app',
    iosBundleId: 'com.example.latihanfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRFV7agRCyJpckLeYOpEgzXlCqopvd_1A',
    appId: '1:86783075117:web:5fbd047099f42244f6e9a4',
    messagingSenderId: '86783075117',
    projectId: 'latihanfirebase-12',
    authDomain: 'latihanfirebase-12.firebaseapp.com',
    databaseURL: 'https://latihanfirebase-12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanfirebase-12.firebasestorage.app',
    measurementId: 'G-Y9GL34ZLHJ',
  );
}
